### ISSUE TITLE
Stuck in "Waiting for the Editor to connect"

### ISSUE THREAD

**Issue by Salman2301** [wix-incubator/corvid#177]
# **Describe**
I initiate a new corvid app using `npx create-corvid-app folderName URL`, the Auth is succeeded but then it always stuck in "Waiting for the Editor to connect". I have run this code in Windows 10 and Ubuntu and also try different Wix website end up in the same result.
It was working before had an issue with windows 10 Admin privileged after I run it as an administrator, it was fixed thanks to @tomenden 
This a new issue is been only for a few days, which i can't able to fix it used different OS or node versions.

Thanks to @tomenden, I run the code with corvid-debug and attach the session log and screenshot of the error as follows

**To Reproduce**
Steps to reproduce the behavior for corvid in debug mode:
1. Open terminal run in a new folder `yarn add corvid-cli`
2. then run `npx corvid-debug clone {your site url here}`
3. and then after the Auth is been verified in the Electron sign in window
4.  the Editor starts and stuck in loading in electron app
5. And on the cmd it's stuck in "Waiting for the Editor to connect"

**Expected behavior**
After the Editor is connected it should ask as to run `npx corvid open-editor`
and after it run we may need to use the editor
**Screenshots**

![Screenshot of chrome dev ](https://user-images.githubusercontent.com/40920317/72687356-0e141700-3b0e-11ea-9b07-5a64ef34f1fb.jpg)
![CMD error](https://user-images.githubusercontent.com/40920317/72687362-19674280-3b0e-11ea-83d2-f9b9ebdccef0.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Node 10.13.0

**Additional context**
Here is the session log file : 
[session.log](https://github.com/wix-incubator/corvid/files/4083440/session.log)

Let me know if you guys any other details
Thanks

**Comment by Salman2301** [comment]
This is fixed Closing this issue

**Comment by attakorns** [comment]
I'm still having this issue today. Did you do something it @Salman2301 ?

**Comment by minhoyooDEV** [comment]
same

**Comment by Salman2301** [comment]
@attakorns that was fixed, you might have some other bug that causing the editor stuck
Create a new issue with instruction to reproduce and send the log as i did for this bug.
That's the best way to get it fixed

**Comment by sm00thslp** [comment]
Issue closed, moved, comes back here...where is your solution?!?! Like wtf!?!

**Comment by etroimcasso** [comment]
This is NOT fixed. I've been having this issue for months, and now you guys are just gonna ignore it instead. Lovely. Moving away from Wix ASAP

**Comment by dor-itzhaki** [comment]
There seems to be a mix of different issues in this thread.
A new corvid-cli version has just been published that fixes an issue preventing login.
Please try again with the latest version (v0.2.12) and if any problem arises open a new issue.
Also please remember that this product is still in alpha stage.
Thanks!

**Comment by attakorns** [comment]
I can confirm that I am no longer stuck at 'Waiting for the editor to connect'. Many thanks!

**Comment by bwprado** [comment]
I just installed everything and I'm getting stuck at "Waiting for editor..."

When I try to open the editor, it says it cannot be opened cause the project is empty.

**Comment by dor-itzhaki** [comment]
@bwprado
If your site has been built using EditorX, note that corvid-cli doesn't currently support it.
If it was built using the classic editor, please open a new issue about your case and try to add as many details as possible.
Specifically, if you can try cloning in debug mode (`corvid-debug` instead of `corvid`), that'll allow us to get much more info about the error.

**Comment by bwprado** [comment]
> 
> 
> @bwprado
> If your site has been built using EditorX, note that corvid-cli doesn't currently support it.
> If it was built using the classic editor, please open a new issue about your case and try to add as many details as possible.
> Specifically, if you can try cloning in debug mode (`corvid-debug` instead of `corvid`), that'll allow us to get much more info about the error.

@dor-itzhaki, thank you very much for the reply, and you're right, I was trying to use it on an EditorX website. But as I imagined that it could be an EditorX incompatibility, I also tried with a website built with the classic editor and unfortunately had the same issue. I'll try later again to see if I missed something.
