### ISSUE TITLE
Local Save and Push completely broken

### ISSUE THREAD

**Issue by bdevore17** [wix-incubator/corvid#198]
**Describe the bug**
Unable To Local Save or Push any project

**To Reproduce**
1. Pull a website using `npx corvid pull --override`
2. Open editor using `npx corvid open-editor`
3. Make any change, large or small, to the site using the editor
3. Attempt to either "Local Save", or "Push"
4. Observe that both the above functionalities end up in a state of never ending "loading"

**Expected behavior**
The local save and push functionalities should work as intended. 

**Screenshots**
`None`

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Version 1.14.6

The same behavior has been observed on my colleague's Windows PC (not sure of the version)

**Additional context**
I am unable to either local save or push using the local editor. I first suspected that this may be a site specific issue. However, I have confirmed that it is not. I created a new site using the blank site template and attempted to both local save and push. The issue persisted even on a blank site.

**Comment by kostagersh** [comment]
Fixed

**Comment by bdevore17** [comment]
@kostagersh This issue is still persisting.

**Comment by bdevore17** [comment]
@kostagersh it now appears that while the push animation never stops, push is indeed happening. Local save still does not work.

**Comment by kostagersh** [comment]
@bdevore17 Can you check again?

**Comment by rlemoie12** [comment]
Update from a member of bdevore17's team. 

We are now able to push our local site to the remote repository, however, I am just seeing the pushes from local as "Manually Saved" events in the Site History, and the updates are not seen on the Editor nor in the Live Site. 
![image](https://user-images.githubusercontent.com/63804205/81643433-8f602400-93f3-11ea-841f-6e8b7065d171.png)

This occurs when trying to merge differences between versions locally. For instance if I have a folder w/in \src\pages and I replace that folder with one from another snapshot, I can then see those changes in my local editor (and often times in the Site History) but they do not get pushed to the remote repo. I am unable to view the activity in the network log when pushing as I get a `"[corvid] an error has occured. see [.corvid\session.log] for details."` error when I open the network tab in the local editor.

**Comment by kostagersh** [comment]
It's another issue, let's open it
